import { FormEvent, useEffect, useRef, useState } from 'react';
import { Link, useBlocker, useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { Button } from '../../components/ui/Button';
import { adminError, adminRequest } from '../../lib/api/admin';
import s from './AdminConsole.module.css';
import e from './QuestionDrafts.module.css';

const option = z.object({ stableId: z.string().min(1).max(100), text: z.string().max(500), justification: z.string().max(2000) }).strict();
const question = z.object({ stableId: z.string().min(1).max(100), prompt: z.string().max(1000), options: z.array(option).length(4), proposedKey: z.string().max(100), rationale: z.string().max(4000), evidenceQuote: z.string().max(6000) }).strict();
const schema = z.object({ stimulus: z.string().max(6000), questions: z.array(question).min(1).max(5), rightsReference: z.string().max(2000) }).strict();
type Body = z.infer<typeof schema>;
interface Page<T> { items: T[]; hasMore: boolean }
interface Blueprint { id: string; version: string; policyVersion: string; ruleId: string }
interface Row { id: string; title: string; questionCount: number; sourceId: string | null; updatedAt: string }
interface Draft { id: string; blueprintId: string; title: string; body: Body; revision: number; sourceId: string | null; updatedAt: string }
interface Report { passed: boolean; findings: { code: string; path: string }[] }
interface Submission { sourceId: string | null; report: Report }
const base = '/part7-drafts';
function Pager({ page, more, change }: { page: number; more: boolean; change: (n: number) => void }) { return <div className={s.actions}><Button variant="outline" disabled={page === 1} onClick={() => change(page - 1)}>Trước</Button><span>Trang {page}</span><Button variant="outline" disabled={!more} onClick={() => change(page + 1)}>Sau</Button></div>; }

export function Part7DraftListPage() {
  const navigate = useNavigate(); const [page, setPage] = useState(1); const [bpPage, setBpPage] = useState(1); const [rows, setRows] = useState<Page<Row> | null>(null); const [bps, setBps] = useState<Page<Blueprint> | null>(null); const [chosen, setChosen] = useState(''); const [previous, setPrevious] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const op = useRef<{ key: string; id: string }>();
  useEffect(() => { const abort = new AbortController(); setError(''); Promise.all([adminRequest<Page<Row>>(`${base}?page=${page}`, { signal: abort.signal }), adminRequest<Page<Blueprint>>(`${base}/blueprints?page=${bpPage}`, { signal: abort.signal })]).then(([a, b]) => { if (!abort.signal.aborted) { setRows(a); setBps(b); } }).catch(x => { if (!abort.signal.aborted) setError(adminError(x)); }); return () => abort.abort(); }, [page, bpPage]);
  async function create(event: FormEvent) { event.preventDefault(); if (!chosen || busy) return; setBusy(true); setError(''); const key = chosen + ':' + previous.trim(); if (op.current?.key !== key) op.current = { key, id: crypto.randomUUID() }; try { const draft = await adminRequest<Draft>(base, { method: 'POST', body: JSON.stringify({ id: op.current.id, blueprintId: chosen, previousRevisionId: previous.trim() || null }) }); navigate(`/admin/part7-drafts/${draft.id}`); } catch (x) { setError(adminError(x)); } finally { setBusy(false); } }
  return <><header className={s.heading}><div><h1>Biên tập Part 7</h1><p className={s.muted}>Soạn bài đọc, nhóm câu hỏi và bằng chứng trực tiếp.</p></div><Link to="/admin/exams">Quản lý đề</Link></header>{error && <p className={s.error}>{error}</p>}<form className={s.panel} onSubmit={create}><h2>Tạo bản nháp</h2>{bps?.items.map(b => <label className={e.choice} key={b.id}><input type="radio" checked={chosen === b.id} onChange={() => setChosen(b.id)} /><span><strong>{b.version}</strong><small>{b.policyVersion} · {b.ruleId}</small></span></label>)}{bps && <Pager page={bpPage} more={bps.hasMore} change={setBpPage} />}<label className={s.field}>ID nguồn Part 7 cần sửa (tùy chọn)<input className={s.input} value={previous} onChange={x => setPrevious(x.target.value)} /></label><Button disabled={busy || !chosen}>Tạo bản nháp Part 7</Button></form><section className={s.panel}><h2>Bản nháp đã lưu</h2>{!rows && !error && <p>Đang tải…</p>}{rows && <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Nội dung</th><th>Trạng thái</th><th>Cập nhật</th></tr></thead><tbody>{rows.items.map(r => <tr key={r.id}><td><Link to={`/admin/part7-drafts/${r.id}`}>{r.title}</Link><span className={s.id}>{r.questionCount} câu</span></td><td>{r.sourceId ? 'Đã tạo nguồn kiểm định' : 'Đang biên tập'}</td><td>{new Date(r.updatedAt).toLocaleString('vi-VN')}</td></tr>)}</tbody></table></div>}{rows && <Pager page={page} more={rows.hasMore} change={setPage} />}</section></>;
}

const labels: Record<string, string> = { STIMULUS_REQUIRED: 'Bài đọc không được để trống.', GROUP_SIZE_INVALID: 'Số câu phải đúng với blueprint.', QUESTION_ID_INVALID: 'Mã câu hỏi phải duy nhất.', QUESTION_PROMPT_INVALID: 'Nội dung câu hỏi không hợp lệ.', RATIONALE_REQUIRED: 'Cần giải thích đáp án.', OPTION_COUNT: 'Mỗi câu cần bốn lựa chọn.', OPTION_INVALID: 'Lựa chọn trống, trùng hoặc thiếu giải thích.', KEY_INVALID: 'Đáp án đúng không thuộc danh sách.', EVIDENCE_REQUIRED: 'Cần trích dẫn bằng chứng.', EVIDENCE_OFFSET_INVALID: 'Trích dẫn phải xuất hiện đúng một lần trong bài đọc.', EVIDENCE_SOURCE_MISMATCH: 'Trích dẫn không khớp bài đọc.', PROVENANCE_REQUIRED: 'Cần ghi nguồn và quyền sử dụng.' };
export function Part7DraftEditorPage() { const { draftId = '' } = useParams(); return <Editor key={draftId} id={draftId} />; }
function Editor({ id }: { id: string }) {
  const navigate = useNavigate(); const [draft, setDraft] = useState<Draft | null>(null); const [title, setTitle] = useState(''); const [text, setText] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [report, setReport] = useState<Report | null>(null); const [busy, setBusy] = useState(false); const [reload, setReload] = useState(0); const pending = useRef<{ expectedRevision: number; title: string; body: Body } | null>(null); const clone = useRef(crypto.randomUUID());
  const parsed = schema.safeParse((() => { try { return JSON.parse(text); } catch { return null; } })()); const dirty = !!draft && (text !== JSON.stringify(draft.body, null, 2) || title !== draft.title); const blocker = useBlocker(dirty || !!pending.current);
  function accept(value: Draft) { setDraft(value); setTitle(value.title); setText(JSON.stringify(value.body, null, 2)); pending.current = null; setReport(null); }
  useEffect(() => { const abort = new AbortController(); setBusy(true); adminRequest<Draft>(`${base}/${id}`, { signal: abort.signal }).then(d => { if (!abort.signal.aborted) accept(d); }).catch(x => { if (!abort.signal.aborted) setError(adminError(x)); }).finally(() => { if (!abort.signal.aborted) setBusy(false); }); return () => abort.abort(); }, [id, reload]);
  useEffect(() => { if (!dirty && !pending.current) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; addEventListener('beforeunload', warn); return () => removeEventListener('beforeunload', warn); }, [dirty]);
  async function save() { if (!draft || !parsed.success || busy) return; setBusy(true); setError(''); const request = pending.current ?? { expectedRevision: draft.revision, title, body: parsed.data }; pending.current = request; try { accept(await adminRequest<Draft>(`${base}/${id}`, { method: 'PUT', body: JSON.stringify(request) })); setNotice('Đã lưu bản nháp.'); } catch (x) { setError(adminError(x)); } finally { setBusy(false); } }
  async function check(submit: boolean) { if (!draft || dirty || busy || pending.current) return; setBusy(true); setError(''); try { const result = await adminRequest<Submission>(`${base}/${id}/${submit ? 'submit' : 'validate'}`, { method: 'POST', body: JSON.stringify({ expectedRevision: draft.revision }) }); setReport(result.report); if (result.sourceId) { setDraft({ ...draft, sourceId: result.sourceId }); accept(await adminRequest<Draft>(`${base}/${id}`)); setNotice('Đã tạo nguồn Part 7 chờ kiểm định.'); } } catch (x) { setError(adminError(x)); } finally { setBusy(false); } }
  async function revise() { if (!draft?.sourceId || busy) return; setBusy(true); try { const next = await adminRequest<Draft>(base, { method: 'POST', body: JSON.stringify({ id: clone.current, blueprintId: draft.blueprintId, previousRevisionId: draft.sourceId }) }); navigate(`/admin/part7-drafts/${next.id}`); } catch (x) { setError(adminError(x)); } finally { setBusy(false); } }
  return <><header className={s.heading}><div><h1>Nhóm câu hỏi Part 7</h1><p className={s.muted}>{draft ? `Bản lưu ${draft.revision}` : 'Đang tải…'}</p></div><Link to="/admin/part7-drafts">Danh sách</Link></header>{error && <p className={s.error}>{error}</p>}{notice && <p className={e.notice}>{notice}</p>}{blocker.state === 'blocked' && <div className={e.notice}>Có nội dung chưa lưu. <Button onClick={() => blocker.reset()}>Ở lại</Button> <Button variant="danger" onClick={() => blocker.proceed()}>Rời trang</Button></div>}{draft && <><section className={s.panel}><label className={s.field}>Tên nội bộ<input className={s.input} disabled={busy || !!draft.sourceId} maxLength={200} value={title} onChange={x => setTitle(x.target.value)} /></label><label className={s.field}>Nội dung JSON<textarea className={s.input} rows={28} spellCheck={false} disabled={busy || !!draft.sourceId} value={text} onChange={x => { setText(x.target.value); setReport(null); }} /></label>{!parsed.success && <p className={s.error}>JSON cần có stimulus, questions (1–5), rightsReference; mỗi câu có stableId, prompt, bốn options, proposedKey, rationale và evidenceQuote.</p>}<p className={s.muted}>evidenceQuote phải được sao chép nguyên văn và xuất hiện đúng một lần trong stimulus. Số câu phải đúng groupSize của blueprint.</p></section>{parsed.success && <div className={e.columns}><section className={s.panel}><h2>Bài đọc</h2><p className={e.text}>{parsed.data.stimulus || 'Chưa có bài đọc.'}</p></section><section className={s.panel}><h2>Xem trước câu hỏi</h2>{parsed.data.questions.map((q, i) => <article key={q.stableId}><h3>{i + 1}. {q.prompt}</h3><ol type="A">{q.options.map(o => <li key={o.stableId}>{o.text}{o.stableId === q.proposedKey ? ' — Đáp án đúng' : ''}</li>)}</ol><blockquote>{q.evidenceQuote}</blockquote><p>{q.rationale}</p></article>)}</section></div>}{report && <section className={s.panel}><h2>{report.passed ? 'Kiểm tra cấu trúc đạt' : 'Cần sửa nội dung'}</h2><ul>{report.findings.map((f, i) => <li key={i}>{labels[f.code] ?? f.code}<span className={s.id}>{f.path}</span></li>)}</ul></section>}{draft.sourceId ? <section className={s.panel}><p>Nguồn đã khóa: <span className={s.id}>{draft.sourceId}</span></p><Button onClick={revise}>Tạo phiên bản sửa đổi</Button></section> : <div className={e.toolbar}><Button disabled={busy || !parsed.success || (!dirty && !pending.current) || !title.trim()} onClick={save}>{pending.current ? 'Thử lưu lại' : 'Lưu nháp'}</Button><Button variant="outline" disabled={busy || dirty || !!pending.current} onClick={() => check(false)}>Kiểm tra cấu trúc</Button><Button disabled={busy || dirty || !!pending.current || !report?.passed} onClick={() => check(true)}>Tạo nguồn chờ kiểm định</Button><Button variant="text" disabled={busy} onClick={() => setReload(x => x + 1)}>Tải bản máy chủ</Button></div>}</>}</>;
}
